### PR TITLE
Added Scrollview removed layout non framed button added text with size

### PR DESCRIPTION
**Pull request by onurhuseyincantay**
I did test it a bit I see redundant for loops for ListView didn't touch that part removed the color with frame added sub element with frame that is auto calculated via geometryreader this means basically its sub views has a calculated frame it might that your elements were way more bigger than expected I did test the sample and it works fine for me 👍

### CODE REVIEW

**Comment by danielsaidi** [comment]
@onurhuseyincantay Wow, the grids work so much better with these changes! Do you have any ideas how to fix the slow horizontal scroll in the first tab's list rows?

**Comment by onurhuseyincantay** [comment]
> @onurhuseyincantay Wow, the grids work so much better with these changes! Do you have any ideas how to fix the slow horizontal scroll in the first tab's list rows?

I did some changes will push in a minute

**Comment by danielsaidi** [comment]
@onurhuseyincantay I still don't understand why the grid item change improve performance?

**Comment by onurhuseyincantay** [comment]
@danielsaidi  its because the item size needs to be calculated and constructed Colors are not a good baseline for views apparently, every element either needs a fixed size or a autolayouted sub element, its the same for UIKit if you have massive elements (even the visibility is not massive) you will get performance issues + keep in mind that this is a simulator and debug mode output so it will definitely be better on a real device.

**Comment by danielsaidi** [comment]
Hmmm ok, so the frame I applied on the color didn't do anything to fix the performance, since color is greedy?

```
Button(action: { print("\(index)") }) {
    Color.red.frame(width: 200, height: 200)
}
```

**Pull request merged**
